baseurl: /
languageCode: en-US
title: Chris Turner
disqusShortname: ''
googleAnalytics: ''
theme: hugo-sustain
permalinks:
  post: /post/:year/:month/:day/:slug
params:
  about: I love all things computer science and maths.
  author: Chris Turner
  avatar: profile.png
  custom_css: []
  custom_js: []
  occupation: Software Engineer
  social:
    Email: email@example.com
    Github: username
    LinkedIn: username
    Twitter: username
menu:
  main:
    - identifier: blog
      name: blog
      url: /post/
      weight: 100
    - identifier: projects
      name: projects
      url: /projects/
      weight: 200
    - identifier: resume
      name: resume
      url: /resume/
      weight: 300

markup:
  goldmark:
    renderer:
      unsafe: true
